data_source:
  type: "csv"
  parameters:
    path: "src/main/resources/sample/transactions.csv"
    date_format: "ISO_OFFSET_DATE_TIME"

filters:
  - type: "status_filter"
    parameters:
      parameters:
        - "COMPLETED"
  - type: "amount_filter"
    parameters:
      min_amount: 10
      max_amount: 1000000

analytics:
  - type: "top_merchants"
    parameters:
      top_n: 5
      by: "value"
  - type: "channel_performance"
  - type: "fraud_detection"
    parameters:
      velocity_window: "1h"
      velocity_threshold: 5
      amount_threshold: 10000

output:
  type: "console"
  parameters: {}
# To write to file or API, change type and provide parameters.path or parameters.endpoint